---
framework: jest
preRun:
     command:
        - npm ci
        - npm run build
preMerge:
  pattern:
    - "./test/**/*.spec.ts"
postMerge:
  pattern:
    - "./test/**/*.spec.ts"
postRun:
     command:
        - node --version
configFile: jest.config.js
version: 1.0
