---
framework: jest
preRun:
     command:
        - npm ci
        - npm run build
preMerge:
  pattern:
    - "./test/**/formatProdErrorMessage.spec.ts"
postMerge:
  pattern:
    - "./test/**/formatProdErrorMessage.spec.ts"
postRun:
     command:
        - node --version
configFile: jest.config.js
parallelism: 4
version: 1.0.0
